---
title: "Assessing the Population-level Conservation Effects of Marine Protected Areas"
subtitle: Cover Page
date: "`r Sys.Date()`"
output:
  bookdown::word_document2:
    reference_docx: uw.docx
  pdf_document: default
  word_document: default
---


## Article Impact Statement

Healthy marine ecosystems are critical to the well-being of the planet. Marine protected areas (MPAs) are increasingly being used to conserve and manage these ecosystems. We pair theory with empirical methods to show that the population-level conservation effects of marine protected areas can be highly variable and challenging to detect. We find no statistically clear effect of a large and well protected network of MPAs in the Channel Island, California, on targeted fin-fish after 14 years of protection, which our simulation analysis suggests is in fact to be expected. MPA practitioners must clearly communicate expectations from MPA networks, and plan monitoring and adaptations strategies that directly address the challenges of estimating population-level conservation effects of protected areas. 

## Running Head

The Population Effects of MPAS

## Keywords:

Marine Protected Area Networks

Marine Conservation

Program Evaluation

Causal Inference

Bio-economic Modeling
  
## Word Count

6000

## Author Details

Jennifer E. Caselle
UCSB Marine Science Institute Bldg 520 Rm 4002 Fl 4L 
Santa Barbara, CA 93106-6150 USA
caselle@msi.ucsb.edu

Christopher Costello
Bren Hall 4410 
University of California, Santa Barbara
Santa Barbara, CA 93106-6150 USA
costello@bren.ucsb.edu

Olivier Deschenes
2127 North Hall
University of California, Santa Barbara
Santa Barbara, CA 93106-6150 USA
olivier@econ.ucsb.edu

Steven D. Gaines
Bren Hall 2410 
University of California, Santa Barbara
Santa Barbara, CA 93106-6150 USA
gaines@bren.ucsb.edu

Ray Hilborn
FSH 352B
University of Washington
1122 NE Boat Street
Seattle, WA 98195-5020 USA

Owen Liu
Bren Hall 4330 
University of California, Santa Barbara
Santa Barbara, CA 93106-6150 United States
owen.r.liu@gmail.com 

## Corresponding Author

Daniel Ovando
Fishery Science Building
University of Washington
1122 NE Boat Street, Seattle, WA 98195-5020 USA
danovan@uw.edu
phone: (805) 284 6864

## Acknowledgements

Funding for the simulation model was provided by the NMFS-Sea Grant Population and Ecosystem Dynamics Fellowship. Empirical data collection was funded primarily by the David and Lucille Packard Foundation in support of the Partnership for Interdisciplinary Studies of Coastal Oceans (PISCO) with additional funding from the California Ocean Protection Council and California SeaGrant. This study would not be possible without the work provided by PISCO divers over the years, with special thanks to to K. Davis Koehn and A. Parsons-Field. We also thank C. Szuwalski, J. Lawson, A. Punt, Chris Brown, and two anonymous reviewers for helpful comments and technical support.



